//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAM.NHModelingLanguage
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "nhml";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"NHModelingLanguage";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"EPAM";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID NHModelingLanguageDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(NHModelingLanguageCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID NHModelingLanguageExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(NHModelingLanguageCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewNHModelingLanguageExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(NHModelingLanguageCommandSetId), 0x0001);
	
		// Package identifier
		public const string NHModelingLanguagePackageId = "ac482944-ef91-4a4c-9e92-0278bf2f4d02";
		
		// Editor factory identifier
		public const string NHModelingLanguageEditorFactoryId = "7fd70b7a-c21a-4968-b82b-2370acfbe125";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string NHModelingLanguageModelExplorerToolWindowId = "00097221-569f-4c10-8c69-76866dc4a379";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace EPAM.NHModelingLanguage
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string NHModelingLanguageCommandSetId = "6fa724ef-d575-400d-989d-d9ad98d2c5cc";
	}
}