//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;
namespace EPAM.NHModelingLanguage
{
	/// <summary>
	/// DomainModel NHModelingLanguageDomainModel
	/// Description for EPAM.NHModelingLanguage.NHModelingLanguage
	/// </summary>
	[DslDesign::DisplayNameResource("EPAM.NHModelingLanguage.NHModelingLanguageDomainModel.DisplayName", typeof(global::EPAM.NHModelingLanguage.NHModelingLanguageDomainModel), "SKBKontur.NHModelingLanguage.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("EPAM.NHModelingLanguage.NHModelingLanguageDomainModel.Description", typeof(global::EPAM.NHModelingLanguage.NHModelingLanguageDomainModel), "SKBKontur.NHModelingLanguage.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.CoreDomainModel))]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.Diagrams.CoreDesignSurfaceDomainModel))]
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
	[DslModeling::DomainObjectId("baa4afbf-ed87-4c68-b177-6dd2f3acd851")]
	public partial class NHModelingLanguageDomainModel : DslModeling::DomainModel
	{
		#region Constructor, domain model Id
	
		/// <summary>
		/// NHModelingLanguageDomainModel domain model Id.
		/// </summary>
		public static readonly global::System.Guid DomainModelId = new global::System.Guid(0xbaa4afbf, 0xed87, 0x4c68, 0xb1, 0x77, 0x6d, 0xd2, 0xf3, 0xac, 0xd8, 0x51);
	
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="store">Store containing the domain model.</param>
		public NHModelingLanguageDomainModel(DslModeling::Store store)
			: base(store, DomainModelId)
		{
			// Call the partial method to allow any required serialization setup to be done.
			this.InitializeSerialization(store);		
		}
		
	
		///<Summary>
		/// Defines a partial method that will be called from the constructor to
		/// allow any necessary serialization setup to be done.
		///</Summary>
		///<remarks>
		/// For a DSL created with the DSL Designer wizard, an implementation of this 
		/// method will be generated in the GeneratedCode\SerializationHelper.cs class.
		///</remarks>
		partial void InitializeSerialization(DslModeling::Store store);
	
	
		#endregion
		#region Domain model reflection
			
		/// <summary>
		/// Gets the list of generated domain model types (classes, rules, relationships).
		/// </summary>
		/// <returns>List of types.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override global::System.Type[] GetGeneratedDomainModelTypes()
		{
			return new global::System.Type[]
			{
				typeof(NHModel),
				typeof(Entity),
				typeof(Property),
				typeof(NHModelHasEntities),
				typeof(EntityHasProperties),
				typeof(EntityInheritedParent),
				typeof(NHDiagram),
				typeof(InheritanceConnector),
				typeof(EntityShape),
				typeof(global::EPAM.NHModelingLanguage.FixUpDiagram),
				typeof(global::EPAM.NHModelingLanguage.ConnectorRolePlayerChanged),
				typeof(global::EPAM.NHModelingLanguage.CompartmentItemAddRule),
				typeof(global::EPAM.NHModelingLanguage.CompartmentItemDeleteRule),
				typeof(global::EPAM.NHModelingLanguage.CompartmentItemRolePlayerChangeRule),
				typeof(global::EPAM.NHModelingLanguage.CompartmentItemRolePlayerPositionChangeRule),
				typeof(global::EPAM.NHModelingLanguage.CompartmentItemChangeRule),
			};
		}
		/// <summary>
		/// Gets the list of generated domain properties.
		/// </summary>
		/// <returns>List of property data.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override DomainMemberInfo[] GetGeneratedDomainProperties()
		{
			return new DomainMemberInfo[]
			{
				new DomainMemberInfo(typeof(Entity), "Name", Entity.NameDomainPropertyId, typeof(Entity.NamePropertyHandler)),
				new DomainMemberInfo(typeof(Property), "Name", Property.NameDomainPropertyId, typeof(Property.NamePropertyHandler)),
				new DomainMemberInfo(typeof(Property), "Type", Property.TypeDomainPropertyId, typeof(Property.TypePropertyHandler)),
				new DomainMemberInfo(typeof(Property), "DisplayName", Property.DisplayNameDomainPropertyId, typeof(Property.DisplayNamePropertyHandler)),
			};
		}
		/// <summary>
		/// Gets the list of generated domain roles.
		/// </summary>
		/// <returns>List of role data.</returns>
		protected sealed override DomainRolePlayerInfo[] GetGeneratedDomainRoles()
		{
			return new DomainRolePlayerInfo[]
			{
				new DomainRolePlayerInfo(typeof(NHModelHasEntities), "NHModel", NHModelHasEntities.NHModelDomainRoleId),
				new DomainRolePlayerInfo(typeof(NHModelHasEntities), "Entity", NHModelHasEntities.EntityDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntityHasProperties), "Entity", EntityHasProperties.EntityDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntityHasProperties), "Property", EntityHasProperties.PropertyDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntityInheritedParent), "SourceEntity", EntityInheritedParent.SourceEntityDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntityInheritedParent), "TargetEntity", EntityInheritedParent.TargetEntityDomainRoleId),
			};
		}
		#endregion
		#region Factory methods
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementMap;
	
		/// <summary>
		/// Creates an element of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementType">Element type which belongs to this domain model.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		public sealed override DslModeling::ModelElement CreateElement(DslModeling::Partition partition, global::System.Type elementType, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementType == null) throw new global::System.ArgumentNullException("elementType");
	
			if (createElementMap == null)
			{
				createElementMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(6);
				createElementMap.Add(typeof(NHModel), 0);
				createElementMap.Add(typeof(Entity), 1);
				createElementMap.Add(typeof(Property), 2);
				createElementMap.Add(typeof(NHDiagram), 3);
				createElementMap.Add(typeof(InheritanceConnector), 4);
				createElementMap.Add(typeof(EntityShape), 5);
			}
			int index;
			if (!createElementMap.TryGetValue(elementType, out index))
			{
				// construct exception error message		
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::EPAM.NHModelingLanguage.NHModelingLanguageDomainModel.SingletonResourceManager.GetString("UnrecognizedElementType"),
								elementType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementType");
			}
			switch (index)
			{
				case 0: return new NHModel(partition, propertyAssignments);
				case 1: return new Entity(partition, propertyAssignments);
				case 2: return new Property(partition, propertyAssignments);
				case 3: return new NHDiagram(partition, propertyAssignments);
				case 4: return new InheritanceConnector(partition, propertyAssignments);
				case 5: return new EntityShape(partition, propertyAssignments);
				default: return null;
			}
		}
	
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementLinkMap;
	
		/// <summary>
		/// Creates an element link of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementLinkType">Element link type which belongs to this domain model.</param>
		/// <param name="roleAssignments">List of relationship role assignments for the new link.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element link.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		public sealed override DslModeling::ElementLink CreateElementLink(DslModeling::Partition partition, global::System.Type elementLinkType, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementLinkType == null) throw new global::System.ArgumentNullException("elementLinkType");
			if (roleAssignments == null) throw new global::System.ArgumentNullException("roleAssignments");
	
			if (createElementLinkMap == null)
			{
				createElementLinkMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(3);
				createElementLinkMap.Add(typeof(NHModelHasEntities), 0);
				createElementLinkMap.Add(typeof(EntityHasProperties), 1);
				createElementLinkMap.Add(typeof(EntityInheritedParent), 2);
			}
			int index;
			if (!createElementLinkMap.TryGetValue(elementLinkType, out index))
			{
				// construct exception error message
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::EPAM.NHModelingLanguage.NHModelingLanguageDomainModel.SingletonResourceManager.GetString("UnrecognizedElementLinkType"),
								elementLinkType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementLinkType");
			
			}
			switch (index)
			{
				case 0: return new NHModelHasEntities(partition, roleAssignments, propertyAssignments);
				case 1: return new EntityHasProperties(partition, roleAssignments, propertyAssignments);
				case 2: return new EntityInheritedParent(partition, roleAssignments, propertyAssignments);
				default: return null;
			}
		}
		#endregion
		#region Resource manager
		
		private static global::System.Resources.ResourceManager resourceManager;
		
		/// <summary>
		/// The base name of this model's resources.
		/// </summary>
		public const string ResourceBaseName = "SKBKontur.NHModelingLanguage.GeneratedCode.DomainModelResx";
		
		/// <summary>
		/// Gets the DomainModel's ResourceManager. If the ResourceManager does not already exist, then it is created.
		/// </summary>
		public override global::System.Resources.ResourceManager ResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return NHModelingLanguageDomainModel.SingletonResourceManager;
			}
		}
	
		/// <summary>
		/// Gets the Singleton ResourceManager for this domain model.
		/// </summary>
		public static global::System.Resources.ResourceManager SingletonResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				if (NHModelingLanguageDomainModel.resourceManager == null)
				{
					NHModelingLanguageDomainModel.resourceManager = new global::System.Resources.ResourceManager(ResourceBaseName, typeof(NHModelingLanguageDomainModel).Assembly);
				}
				return NHModelingLanguageDomainModel.resourceManager;
			}
		}
		#endregion
		#region Copy/Remove closures
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter copyClosure;
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter removeClosure;
		/// <summary>
		/// Returns an IElementVisitorFilter that corresponds to the ClosureType.
		/// </summary>
		/// <param name="type">closure type</param>
		/// <param name="rootElements">collection of root elements</param>
		/// <returns>IElementVisitorFilter or null</returns>
		public override DslModeling::IElementVisitorFilter GetClosureFilter(DslModeling::ClosureType type, global::System.Collections.Generic.ICollection<DslModeling::ModelElement> rootElements)
		{
			switch (type)
			{
				case DslModeling::ClosureType.CopyClosure:
					return NHModelingLanguageDomainModel.CopyClosure;
				case DslModeling::ClosureType.DeleteClosure:
					return NHModelingLanguageDomainModel.DeleteClosure;
			}
			return base.GetClosureFilter(type, rootElements);
		}
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter CopyClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (NHModelingLanguageDomainModel.copyClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter copyFilter = new DslModeling::ChainingElementVisitorFilter();
					copyFilter.AddFilter(new NHModelingLanguageCopyClosure());
					copyFilter.AddFilter(new DslModeling::CoreCopyClosure());
					copyFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceCopyClosure());
					
					NHModelingLanguageDomainModel.copyClosure = copyFilter;
				}
				return NHModelingLanguageDomainModel.copyClosure;
			}
		}
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter DeleteClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (NHModelingLanguageDomainModel.removeClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter removeFilter = new DslModeling::ChainingElementVisitorFilter();
					removeFilter.AddFilter(new NHModelingLanguageDeleteClosure());
					removeFilter.AddFilter(new DslModeling::CoreDeleteClosure());
					removeFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceDeleteClosure());
		
					NHModelingLanguageDomainModel.removeClosure = removeFilter;
				}
				return NHModelingLanguageDomainModel.removeClosure;
			}
		}
		#endregion
		#region Diagram rule helpers
		/// <summary>
		/// Enables rules in this domain model related to diagram fixup for the given store.
		/// If diagram data will be loaded into the store, this method should be called first to ensure
		/// that the diagram behaves properly.
		/// </summary>
		public static void EnableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.EnableRule(typeof(global::EPAM.NHModelingLanguage.FixUpDiagram));
			ruleManager.EnableRule(typeof(global::EPAM.NHModelingLanguage.ConnectorRolePlayerChanged));
			ruleManager.EnableRule(typeof(global::EPAM.NHModelingLanguage.CompartmentItemAddRule));
			ruleManager.EnableRule(typeof(global::EPAM.NHModelingLanguage.CompartmentItemDeleteRule));
			ruleManager.EnableRule(typeof(global::EPAM.NHModelingLanguage.CompartmentItemRolePlayerChangeRule));
			ruleManager.EnableRule(typeof(global::EPAM.NHModelingLanguage.CompartmentItemRolePlayerPositionChangeRule));
			ruleManager.EnableRule(typeof(global::EPAM.NHModelingLanguage.CompartmentItemChangeRule));
		}
		
		/// <summary>
		/// Disables rules in this domain model related to diagram fixup for the given store.
		/// </summary>
		public static void DisableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.DisableRule(typeof(global::EPAM.NHModelingLanguage.FixUpDiagram));
			ruleManager.DisableRule(typeof(global::EPAM.NHModelingLanguage.ConnectorRolePlayerChanged));
			ruleManager.DisableRule(typeof(global::EPAM.NHModelingLanguage.CompartmentItemAddRule));
			ruleManager.DisableRule(typeof(global::EPAM.NHModelingLanguage.CompartmentItemDeleteRule));
			ruleManager.DisableRule(typeof(global::EPAM.NHModelingLanguage.CompartmentItemRolePlayerChangeRule));
			ruleManager.DisableRule(typeof(global::EPAM.NHModelingLanguage.CompartmentItemRolePlayerPositionChangeRule));
			ruleManager.DisableRule(typeof(global::EPAM.NHModelingLanguage.CompartmentItemChangeRule));
		}
		#endregion
	}
		
	#region Copy/Remove closure classes
	/// <summary>
	/// Remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class NHModelingLanguageDeleteClosure : NHModelingLanguageDeleteClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public NHModelingLanguageDeleteClosure() : base()
		{
		}
	}
	
	/// <summary>
	/// Base class for remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class NHModelingLanguageDeleteClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public NHModelingLanguageDeleteClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::EPAM.NHModelingLanguage.NHModelHasEntities.EntityDomainRoleId, true);
			DomainRoles.Add(global::EPAM.NHModelingLanguage.EntityHasProperties.PropertyDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			return DslModeling::VisitorFilterResult.Yes;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			if (targetDomainRole == null) throw new global::System.ArgumentNullException("targetDomainRole");
			return this.DomainRoles.Contains(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Specialized.HybridDictionary();
				}
				return this.domainRoles;
			}
		}
	
	}
	/// <summary>
	/// Copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class NHModelingLanguageCopyClosure : NHModelingLanguageCopyClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public NHModelingLanguageCopyClosure() : base()
		{
		}
	}
	/// <summary>
	/// Base class for copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class NHModelingLanguageCopyClosureBase : DslModeling::CopyClosureFilter, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public NHModelingLanguageCopyClosureBase():base()
		{
		}
	}
	#endregion
		
}
namespace EPAM.NHModelingLanguage
{
	/// <summary>
	/// DomainEnumeration: TypeEnum
	/// Description for EPAM.NHModelingLanguage.TypeEnum
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum TypeEnum
	{
		/// <summary>
		/// String
		/// Description for EPAM.NHModelingLanguage.TypeEnum.String
		/// </summary>
		[DslDesign::DescriptionResource("EPAM.NHModelingLanguage.TypeEnum/String.Description", typeof(global::EPAM.NHModelingLanguage.NHModelingLanguageDomainModel), "SKBKontur.NHModelingLanguage.GeneratedCode.DomainModelResx")]
		String,
		/// <summary>
		/// Int32
		/// Description for EPAM.NHModelingLanguage.TypeEnum.Int32
		/// </summary>
		[DslDesign::DescriptionResource("EPAM.NHModelingLanguage.TypeEnum/Int32.Description", typeof(global::EPAM.NHModelingLanguage.NHModelingLanguageDomainModel), "SKBKontur.NHModelingLanguage.GeneratedCode.DomainModelResx")]
		Int32,
		/// <summary>
		/// Decimal
		/// Description for EPAM.NHModelingLanguage.TypeEnum.Decimal
		/// </summary>
		[DslDesign::DescriptionResource("EPAM.NHModelingLanguage.TypeEnum/Decimal.Description", typeof(global::EPAM.NHModelingLanguage.NHModelingLanguageDomainModel), "SKBKontur.NHModelingLanguage.GeneratedCode.DomainModelResx")]
		Decimal,
	}
}

